### ISSUE TITLE
ApplicationError 7

### ISSUE THREAD

**Issue by tucotuco** [VertNet/webapp#450]
During downloads, under circumstances currently mysterious, an unknown error exception is thrown. This may result in loss of downloaded records or of download files altogether.

ApplicationError: 7 
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1536, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1530, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~vertnet-portal/tuco.375280118385007457/vertnet/service/download.py", line 97, in post
    files.finalize(writable_file_name)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/files/file.py", line 568, in finalize
    f.close(finalize=True)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/files/file.py", line 291, in close
    self._make_rpc_call_with_retry('Close', request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/files/file.py", line 427, in _make_rpc_call_with_retry
    _make_call(method, request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/files/file.py", line 252, in _make_call
    _raise_app_error(e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/files/file.py", line 186, in _raise_app_error
    raise UnknownError(e)
UnknownError: ApplicationError: 7

**Comment by tucotuco** [comment]
It looks like the download API uses a files API that will be deprecated entirely. See https://cloud.google.com/appengine/docs/python/googlestorage/. This will need to be re-engineered.

**Comment by tucotuco** [comment]
Removed the dependency on the Google Files API. Should solve this problem.
