### ISSUE TITLE
Invalid request URLs writing to CartoDB

### ISSUE THREAD

**Issue by tucotuco** [VertNet/webapp#455]
Does this result from trying to track something with too many resources involved, making the URL too long? Or is it something else?

Invalid request URL: http://vertnet.cartodb.com/api/v2/sql?q=INSERT+INTO+query_log%28client%2Cquery%2Cerror%2Ctype%2Ccount%2Cdownloader%2Cdownload%2Clat%2Clon%2C+results_by_resource%29+VALUES+%28%27portal-prod%27%2C%2712599%27%2C%27%27%2C%27query%27%2C317%2C%27%27%2C%27%27%2C19.432608%2C-99.133208%2C%27%7B%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dcumv_amph%22%3A+1%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dcumv_rept%22%3A+1%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dcumv_mamm%22%3A+1%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fiptstrays%2Fresource.do%3Fr%3Dtubri_fish%22%3A+1%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Ddmnh_birds%22%3A+1%2C+%22http%3A%2F%2Fdigir.mcz.harvard.edu%2Fipt%2Fresource.do%3Fr%3Dmcz_subset_for_vertnet%22%3A+4%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dnysm_birds%22%3A+1%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dpsm_verts%22%3A+3%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dummz_birds%22%3A+3%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dmvz_mammal%22%3A+15%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dcuml_sound_film%22%3A+1%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dmvz_egg%22%3A+1%2C+%22http%3A%2F%2Fipt.nhm.ku.edu%2Fipt%2Fresource.do%3Fr%3Dkubi_ichthyology%22%3A+1%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Duam_mamm%22%3A+2%2C+%22http%3A%2F%2Fipt.nhm.ku.edu%2Fipt%2Fresource.do%3Fr%3Dkubi_ornithology_tissue%22%3A+1%2C+%22http%3A%2F%2Fipt.calacademy.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dmam%22%3A+1%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dcumv_bird%22%3A+1%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dmvz_herp%22%3A+3%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dmsb_mamm%22%3A+3%2C+%22http%3A%2F%2Fgbif.rom.on.ca%3A8180%2Fipt%2Fresource.do%3Fr%3Dherps%22%3A+1%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dlacm_verts%22%3A+26%2C+%22http%3A%2F%2Fipt.nhm.ku.edu%2Fipt%2Fresource.do%3Fr%3Dkubi_herps%22%3A+1%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dmlz_bird%22%3A+1%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dlsumz_mammals%22%3A+1%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Duam_bird%22%3A+1%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Ddmns_mamm%22%3A+1%2C+%22http%3A%2F%2Fgbif.rom.on.ca%3A8180%2Fipt%2Fresource.do%3Fr%3Dbirdspass%22%3A+2%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Ddmns_bird%22%3A+1%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dmvz_bird%22%3A+3%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Ducm_birds%22%3A+1%2C+%22http%3A%2F%2Fipt.calacademy.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dorn%22%3A+1%2C+%22http%3A%2F%2Fipt.nhm.ku.edu%2Fipt%2Fresource.do%3Fr%3Dkubi_mammals%22%3A+1%2C+%22http%3A%2F%2Fiptsnomnh.cloudapp.net%3A8080%2Fipt%2Fresource.do%3Fr%3Damphibian%22%3A+3%2C+%22http%3A%2F%2Ffmipt.fieldmuseum.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dfmnh_mammals%22%3A+2%2C+%22http%3A%2F%2Fiptsnomnh.cloudapp.net%3A8080%2Fipt%2Fresource.do%3Fr%3Dbirds%22%3A+1%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dutep_verts%22%3A+1%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dcm_herps%22%3A+1%2C+%22http%3A%2F%2Fipt.calacademy.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dherp%22%3A+3%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dtnhc_herps%22%3A+1%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dnysm_mammals%22%3A+1%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dummz_mammals%22%3A+1%7D%27%29%3Bupdate+query_log+set+the_geom+%3D+CDB_LatLng%28lat%2Clon%29&api_key=b3263ddb2c8afddfa4bddca43d44727f9d3220ce
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in **call**
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in **call**
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in **call**
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(_args, *_kwargs)
  File "/base/data/home/apps/s~vertnet-portal/prod.375513608972966574/vertnet/service/tracker.py", line 48, in post
    rpc.get_result()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 612, in get_result
    return self.__get_result_hook(self)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/urlfetch.py", line 389, in _get_fetch_result
    'Invalid request URL: ' + url + error_detail)
InvalidURLError: Invalid request URL: http://vertnet.cartodb.com/api/v2/sql?q=INSERT+INTO+query_log%28client%2Cquery%2Cerror%2Ctype%2Ccount%2Cdownloader%2Cdownload%2Clat%2Clon%2C+results_by_resource%29+VALUES+%28%27portal-prod%27%2C%2712599%27%2C%27%27%2C%27query%27%2C317%2C%27%27%2C%27%27%2C19.432608%2C-99.133208%2C%27%7B%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dcumv_amph%22%3A+1%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dcumv_rept%22%3A+1%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dcumv_mamm%22%3A+1%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fiptstrays%2Fresource.do%3Fr%3Dtubri_fish%22%3A+1%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Ddmnh_birds%22%3A+1%2C+%22http%3A%2F%2Fdigir.mcz.harvard.edu%2Fipt%2Fresource.do%3Fr%3Dmcz_subset_for_vertnet%22%3A+4%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dnysm_birds%22%3A+1%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dpsm_verts%22%3A+3%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dummz_birds%22%3A+3%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dmvz_mammal%22%3A+15%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dcuml_sound_film%22%3A+1%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dmvz_egg%22%3A+1%2C+%22http%3A%2F%2Fipt.nhm.ku.edu%2Fipt%2Fresource.do%3Fr%3Dkubi_ichthyology%22%3A+1%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Duam_mamm%22%3A+2%2C+%22http%3A%2F%2Fipt.nhm.ku.edu%2Fipt%2Fresource.do%3Fr%3Dkubi_ornithology_tissue%22%3A+1%2C+%22http%3A%2F%2Fipt.calacademy.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dmam%22%3A+1%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dcumv_bird%22%3A+1%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dmvz_herp%22%3A+3%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dmsb_mamm%22%3A+3%2C+%22http%3A%2F%2Fgbif.rom.on.ca%3A8180%2Fipt%2Fresource.do%3Fr%3Dherps%22%3A+1%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dlacm_verts%22%3A+26%2C+%22http%3A%2F%2Fipt.nhm.ku.edu%2Fipt%2Fresource.do%3Fr%3Dkubi_herps%22%3A+1%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dmlz_bird%22%3A+1%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Dlsumz_mammals%22%3A+1%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Duam_bird%22%3A+1%2C+%22http%3A%2F%2Fipt.vertnet.org%3A8080%2Fipt%2Fresource.do%3Fr%3Ddmns_mamm%22%3A+1%2C+%22http%3A%2F%2Fgbif.rom.on.ca%3A8180%2Fipt%2Fresource.do%3Fr%3...(length 9533)

**Comment by laurarussell** [comment]
Is this still an issue?

**Comment by jotegui** [comment]
Have to check whether this is still happening...
