### ISSUE TITLE
Invalid character in URL not trapped

### ISSUE THREAD

**Issue by tucotuco** [VertNet/webapp#456]
From the App Engine Error log:

'ascii' codec can't encode character u'\xf3' in position 152: ordinal not in range(128)
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~vertnet-portal/prod.375513608972966574/vertnet/service/tracker.py", line 44, in post
    log_url = cdb_url % (urllib.urlencode(dict(q=log_sql, api_key=apikey())))
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urllib.py", line 1307, in urlencode
    v = quote_plus(str(v))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 152: ordinal not in range(128)

**Comment by laurarussell** [comment]
is this still an issue?

**Comment by tucotuco** [comment]
Nothing was done to correct it, so it may still exist. However, I haven't seen in in the last month of intensive development and testing. This may have to do with encoding the URLs of the resources to track whose records are in results. This was changed over to use gbifdatasetids instead, so if that was the cause it is no longer a problem. Closing.
