### ISSUE TITLE
Invalid query not trapped

### ISSUE THREAD

**Issue by tucotuco** [VertNet/webapp#457]
From the App Engine error log:
QUERY (mammalia) tissue:1

Results in an exception:

'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~vertnet-portal/prod.375513608972966574/vertnet/service/download.py", line 66, in post
    raise e
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by tucotuco** [comment]
This no longer seems to be a problem. The following returns results with no error:

http://portal.vertnet.org/search?q=(mammalia)+tissue:1
