### ISSUE TITLE
Compose timing out with LARGE download requests

### ISSUE THREAD

**Issue by tucotuco** [VertNet/webapp#568]
With 

http://tuco.vertnet-portal.appspot.com/api/download?q={"q":"country:Canada","n":"canadatest.txt","e":"gtuco.btuco@gmail.com"} 

there are 466267 records successfully written to GCS files. During the compose phase, the first composition attempt times out consistently with the following example error. Compose does make the composed file in the vn-dltest
temporary file bucket, but the response doesn't come back in time. Smaller result sets seem not to suffer this problem.

Error composing file: canadatest3.txt-23fb89b4ea9243f98b716f8d581a67ea-cl-0.tsv Error: The API call urlfetch.Fetch() took too long to respond and was cancelled.
Version: download.py 2015-08-30T18:29:55+02:00
E 2015-08-30 23:34:54.108
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 267, in Handle
    result = handler(dict(self._environ), self._StartResponse)
  File "/base/data/home/apps/s~vertnet-portal/tuco.386806081123595224/lib/engineauth/middleware.py", line 148, in __call__
    resp = req.get_response(self.app)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webob-1.1.1/webob/request.py", line 1086, in get_response
    application, catch_exc_info=False)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webob-1.1.1/webob/request.py", line 1055, in call_application
    app_iter = application(self.environ, start_response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~vertnet-portal/tuco.386806081123595224/vertnet/service/download.py", line 453, in post
    logging.error("Error composing file: %s Error: %s\nVersion: %s"
DeadlineExceededError

**Comment by tucotuco** [comment]
This request sent an apitracker call to insert that never made it into CartoDB and did not produce and error. Log said...

2015-08-30 23:24:54.664
Trying SQL: INSERT INTO query_log_master(             api_version, client, count, download, downloader, error, lat, lon,             matching_records, query, query_version, request_source, response_records,             results_by_resource, type) VALUES (             'api.py 2015-08-30T21:57:25+02:00', 'portal-prod', 466267, '/vn-downloads2/canadatest3.txt-23fb89b4ea9243f98b716f8d581a67ea.tsv', 'gtuco.btuco@gmail.com', 'None', 47.394144, 0.68484,             466267, 'country:Canada', 'search.py 2015-08-29T21:04:44+02:00', 'DownloadAPI', 267,             '{"be5507b9-7abf-4b69-afe1-5ca2b7561734": 6406, "9ce52ff6-01b6-44a2-b617-9bc2ee8e8cd1": 472, "cece4fc2-1fec-4bb5-a335-7252548e3f0b": 496, "b99095f3-d1e9-4902-9938-10ff1711ca5d": 116, "41fc5c40-5e81-496f-9733-6b5681b3b7a5": 1862, "84b018de-f762-11e1-a439-00145eb45e9a": 88, "e90a588b-0eed-4077-8a4f-7e61da35b3f8": 122, "7f6dd0f7-9ed4-49c0-bb71-b2a9c7fed9f1": 6234, "88d8974c-f762-11e1-a439-00145eb45e9a": 176, "2f54cb88-4167-499a-81fb-0a2d02465212": 280, "8934ad0c-f762-11e1-a439-00145eb45e9a": 15, "4e5552d1-5eaf-40a3-b48b-01f92da22f17": 39611, "ba0c046d-52bb-4262-a495-652988c9f3f7": 12002, "f11db245-3f9f-4fc6-a0cc-12b4124d081b": 1184, "84aefc7e-f762-11e1-a439-00145eb45e9a": 264, "acede617-a095-4caa-a93e-4a77f5f77935": 17, "e48d6c49-34a3-4df6-8206-121c061f190d": 504, "temp-flmnh-birds-datasetid": 1783, "afc30a94-6107-488a-b9c0-ba9c4fa68b7c": 677, "9a201e2f-dada-4cb9-88c7-695e391aeb2f": 281, "16e1958f-cb0a-445d-98cf-4073b344f268": 17, "37da8155-b024-4312-9456-9f69d0873c4b": 74, "dce8feb0-6c89-11de-8225-b8a03c50a862": 54, "8be43f9b-52e7-47d4-be3e-dbcc066d70ab": 9328, "905589dd-1f8f-4aee-95e6-5672466e348d": 25, "217b0d4f-c87e-4063-b6c5-78277e40e866": 47, "7c93d290-6c8b-11de-8226-b8a03c50a862": 64, "4e50e3a6-8d31-44bc-ad3d-de6311ad0943": 130, "a82d2421-be5a-4779-babc-da0b634a7ba8": 16934, "08dc18e5-e3c0-4f74-b49a-b8274aabe020": 15, "91aa5e23-9cad-4751-86e0-241da77d7407": 579, "474cd7e1-7620-454f-828c-24907a15d6a7": 22, "961f602a-f762-11e1-a439-00145eb45e9a": 53, "e0dbf705-cec4-4dce-a152-fc4ebe14674d": 4130, "f6e21753-5129-498f-92bd-73710b0087e3": 53431, "8935e64a-f762-11e1-a439-00145eb45e9a": 426, "830fd460-f762-11e1-a439-00145eb45e9a": 2365, "f9772d3a-db34-4a33-baa0-7a016a970358": 1, "9643f840-f762-11e1-a439-00145eb45e9a": 572, "bd2feca8-ec39-4480-9dad-e353ab6a506d": 51, "0debafd0-6c8a-11de-8225-b8a03c50a862": 39, "4852540d-afd1-4678-bd20-4aac28f65e2d": 547, "f96a6f8c-b992-4159-8039-db8f30bac985": 1694, "56caf05f-1364-4f24-85f6-0c82520c2792": 1, "9fbac577-9e5f-41b2-9edb-c2ed1d2c7020": 50, "0daed095-478a-4af6-abf5-18acb790fbb2": 6397, "d499aef2-b1d9-4890-aeb3-5f0d1237b513": 9, "5d6c10bd-ea31-4363-8b79-58c96d859f5b": 647, "3633e0e7-8c25-4c3d-b9c7-078c0be25665": 450, "78122332-6315-41bd-914b-e9c1342d9093": 19, "830eb5d0-f762-11e1-a439-00145eb45e9a": 2545, "609217ee-054d-441d-a850-356cbc2fb385": 82, "7a28b1b1-9d4c-4aeb-b239-38865417b5ea": 31, "847bbbde-f762-11e1-a439-00145eb45e9a": 38, "854f602e-f762-11e1-a439-00145eb45e9a": 685, "9c007868-b667-4c07-9a1a-96b796066f64": 11, "ea9f5b0b-ad97-45ea-935a-ba2784c80cbb": 14, "831234b2-f762-11e1-a439-00145eb45e9a": 1904, "8631295a-f762-11e1-a439-00145eb45e9a": 605, "84e6e5f8-f762-11e1-a439-00145eb45e9a": 60, "5f3463d2-51b6-4a8a-b252-9bab4388934e": 44, "8855595b-a836-4557-b17b-794aadda747a": 30, "cd875b5a-b3fe-48f2-94c7-371cab1431f3": 14691, "5b0cfab4-9145-4fe2-89e3-fcbc294aa5b2": 42, "226b536c-25f9-4f6b-b144-edcbdffa3566": 8, "423d9318-4dd4-4d31-81cb-27778c44a3bc": 1, "c5c4a23e-2035-4416-ab64-032d6df52ddb": 38698, "2ad1ce1d-5f2d-4790-95fa-57a901019d21": 121, "75018539-6328-41de-b875-7c2e61dc1635": 311, "58d0f326-2e85-4d0a-a744-571461220f00": 155, "b8ed9b7c-5b73-4e6d-a6e1-b0911a09f947": 95, "c21cd435-718a-4069-b503-776bf0e22b96": 1429, "35720b3e-aded-4b83-b4f1-967f1d457d6a": 650, "36f15a36-6b45-442e-9c31-cd633423aee0": 7968, "9cd0014c-b7b1-4ed1-bef7-0225acfa4ef2": 34, "76dd8f0d-2daa-4a69-9fcd-55e04230334a": 647, "a8ee9bc6-5914-427d-9fba-f8545250ac34": 210, "4bfac3ea-8763-4f4b-a71a-76a6f5f243d3": 22157, "88d7437e-f762-11e1-a439-00145eb45e9a": 9630, "86594bf6-f762-11e1-a439-00145eb45e9a": 303, "ba0c03ab-fa61-4a3c-8db7-35c8c3454168": 13, "84dbaec2-f762-11e1-a439-00145eb45e9a": 220, "852628c6-f762-11e1-a439-00145eb45e9a": 126, "60805ee8-a17e-48ce-8726-be447e4d8e1d": 3, "dce00a1f-f6b4-4e11-9771-92c62c40ad80": 366, "8658262c-f762-11e1-a439-00145eb45e9a": 2453, "39f021d5-240c-445d-b62f-33bfed94938d": 222, "fcba1f2e-c8b8-491f-8b5f-62fae3157cc7": 138, "5345b34d-82a4-44b7-9d82-5109df1ca243": 243, "eccf4b09-f0c8-462d-a48c-41a7ce36815a": 335, "71e6db8e-f762-11e1-a439-00145eb45e9a": 5, "temp-ansp-ich-datasetid": 449, "2a79f202-3f3a-4d54-88fa-09aa8de1ac73": 61, "6ce7290f-47f6-4046-8356-371f5b6749df": 994, "210babc8-5723-41ac-bb13-c834590dbb15": 5078, "8e479b8f-ac16-4bed-a11a-bc7e27c31663": 419, "3ad882bb-cd21-4201-8b83-3684bfc6d830": 17251, "835ff8be-ea5c-45e4-b3f3-126852ac56fe": 196, "2f897875-210a-43a9-bab3-a724bea8e400": 42, "84e94348-f762-11e1-a439-00145eb45e9a": 11, "847e2306-f762-11e1-a439-00145eb45e9a": 87, "1d04e739-98a9-4e16-9970-8f8f3bf9e9e3": 2354, "c50340a3-54f9-46fa-aecb-6197bcfa1b54": 237, "71d0dff0-f762-11e1-a439-00145eb45e9a": 612, "22a66350-7947-4a49-84a3-39c7c1b0881f": 404, "854cf79e-f762-11e1-a439-00145eb45e9a": 2519, "09c4287e-e6d5-4552-a07f-bff8a00833d8": 878, "5df38344-b821-49c2-8174-cf0f29f4df0d-Birds": 13691, "6d2cfc0a-9903-40b8-802b-403398218e4a": 2643, "5f1568db-5d5b-4597-9c66-dfbd0d7ddd7b": 25, "8f79c802-a58c-447f-99aa-1d6a0790825a": 93, "427a6290-0c65-11dd-84d2-b8a03c50a862": 28, "377be098-626f-4cc2-b4b5-35700050669a": 3557, "813b435e-f762-11e1-a439-00145eb45e9a": 156, "5df38344-b821-49c2-8174-cf0f29f4df0d-Herps": 1061, "fa375330-6c8a-11de-8226-b8a03c50a862": 52, "2f46fe6f-b9fd-4dba-8ca2-2cb1368ceed8": 241, "861d3d64-f762-11e1-a439-00145eb45e9a": 144, "88d5d94e-f762-11e1-a439-00145eb45e9a": 9061, "96c93a1e-f762-11e1-a439-00145eb45e9a": 13279, "84b26828-f762-11e1-a439-00145eb45e9a": 632, "b15d4952-7d20-46f1-8a3e-556a512b04c5": 10135, "f36b26ac-97d1-40f6-a9a0-484defff98e7": 9, "6080b6cc-1c24-41ff-ad7f-0ebe7b56f311": 22, "81e4afd9-0b61-483d-b7fa-0690f06c8e14": 132, "c62f7574-d65a-4018-87a2-b96d6df5231b": 17, "49c45996-3726-468e-be35-eb37cb5b8e45": 49, "8eddc200-f535-4c65-9b4d-f723eafe607e": 2618, "5df38344-b821-49c2-8174-cf0f29f4df0d-Paleo": 416, "7a25f7aa-03fb-4322-aaeb-66719e1a9527": 968, "84b4d6e4-f762-11e1-a439-00145eb45e9a": 174, "136560fa-9eb9-492f-866e-5bd110c52f74": 33322, "3d84f407-8a76-473a-b8c8-54a58d5f581b": 33, "89337996-f762-11e1-a439-00145eb45e9a": 72, "bdce0b4b-9ec3-481b-9f44-683ac1844d1d": 20, "d5fafa95-7de2-48c0-bf10-3480bcca4a2b": 32, "5df38344-b821-49c2-8174-cf0f29f4df0d-Mammals": 18860, "8a5459ee-3d3a-4e0a-9fb0-0cbbb9e5a6f9": 10, "85484744-f762-11e1-a439-00145eb45e9a": 899, "b929f23d-290f-4e85-8f17-764c55b3b284": 1, "3959ee49-7678-4a88-9049-5dfc55ccebf3": 58, "4f29b6ab-20c0-4479-8795-4915bedcebd1": 2041, "96ca66b4-f762-11e1-a439-00145eb45e9a": 8593, "8d88898d-a2c4-4616-a1fe-431b9c06b671": 671, "5df38344-b821-49c2-8174-cf0f29f4df0d-Fish": 1977, "c9076cd3-349f-4068-a5c7-bc34449c3916": 59, "51fa0155-a545-4154-ac20-b89dbb2c312b": 16, "43e0bba3-9edb-4b00-b490-84924e55a222": 1239, "1ebf1564-949e-49ca-9f8b-e11ef68238db": 1, "3a339645-d3b4-40aa-b891-f9c92dc554d8": 250, "62ad511d-d298-4fd7-80e7-f5d5bd32299e": 33, "f58922e2-93ed-4703-ba22-12a0674d1b54": 216, "41a910f3-db13-4520-a3b2-199edb4a32ea": 54, "e3b959d6-fcbe-4a28-a166-e4a807c340a0": 11277, "a6a1d66f-07aa-4618-becd-98d9efadb592": 2, "78dcfcbd-03c4-4d47-8618-830aac6f2ee5": 52, "02242d2f-b43f-44d1-8e53-4c51af461f5b": 3019, "84f3b06c-f762-11e1-a439-00145eb45e9a": 7320, "854f70cc-55e3-4af2-9417-0f47d6c7902d": 101, "717b3b87-0ebd-46b4-812b-4a29786798d9": 766, "96419bea-f762-11e1-a439-00145eb45e9a": 140, "18c93d12-34fb-4d3f-903c-b77215a1dcc9": 4, "df9c8b86-9d36-4e29-91b3-4274dff053e5": 1259, "e6acc36b-4149-4458-a26f-17fbeb0df90b": 4803, "a79c2b50-6c8a-11de-8226-b8a03c50a862": 176, "abcaccad-9e01-4b2a-b493-32531cbed32a": 12}', 'download');
            update query_log_master set the_geom = CDB_LatLng(lat,lon)
URL: http://vertnet.cartodb.com/api/v2/sql?q=INSERT+INTO+query_lo...(length 17816)
I 2015-08-30 23:24:54.767
Tracked successfully.
Version:tracker.py 2015-08-26T21:45:05+02:00

**Comment by tucotuco** [comment]
Solved in fe413a63e6ea350296678143f194da877c8f1e51
